-- MySQL Script generated by MySQL Workbench
-- Fri Dec 10 11:44:37 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
SHOW WARNINGS;
-- -----------------------------------------------------
-- Schema tttt
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `tttt` ;

-- -----------------------------------------------------
-- Schema tttt
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `tttt` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
SHOW WARNINGS;
USE `tttt` ;

-- -----------------------------------------------------
-- Table `benh`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `benh` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `benh` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `ten` VARCHAR(50) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `doituong` VARCHAR(50) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `nguyennhan` VARCHAR(255) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `trieuchung` VARCHAR(255) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `phongngua` VARCHAR(255) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `chitietkho`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `chitietkho` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `chitietkho` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `soluong` INT NOT NULL,
  `idvacxin` INT NOT NULL,
  `idkho` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `chitietphieunhap`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `chitietphieunhap` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `chitietphieunhap` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `soluong` INT NOT NULL,
  `idphieunhap` INT NOT NULL,
  `idvacxin` INT NOT NULL,
  `thanhtien` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 73
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `chitietphieuxuat`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `chitietphieuxuat` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `chitietphieuxuat` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `soluong` INT NOT NULL,
  `idphieuxuat` INT NOT NULL,
  `idvacxin` INT NOT NULL,
  `thanhtien` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `chitietxuatkho`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `chitietxuatkho` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `chitietxuatkho` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `soluong` INT NOT NULL,
  `idchitietkho` INT NOT NULL,
  `idxuatkho` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `dangkytiem`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dangkytiem` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `dangkytiem` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `ten` VARCHAR(200) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `ngaysinh` DATE NULL DEFAULT NULL,
  `sdt` VARCHAR(15) NULL DEFAULT NULL,
  `ngaytiem` DATE NULL DEFAULT NULL,
  `idbenh` INT NULL DEFAULT NULL,
  `idgoi` INT NULL DEFAULT NULL,
  `idtrungtam` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `dieutri`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dieutri` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `dieutri` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `ghichu` VARCHAR(255) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `idvacxin` INT NULL DEFAULT NULL,
  `idbenh` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `goi`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `goi` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `goi` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `ten` VARCHAR(50) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `doituong` VARCHAR(50) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `tongtien` FLOAT NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `goidangky`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `goidangky` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `goidangky` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `idgoi` INT NULL DEFAULT NULL,
  `idkhachhang` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `goidieutri`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `goidieutri` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `goidieutri` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `idgoi` INT NULL DEFAULT NULL,
  `iddieutri` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `hoadon`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hoadon` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `hoadon` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `ngay` DATE NULL DEFAULT NULL,
  `tongtien` FLOAT NULL DEFAULT NULL,
  `idnhanvien` INT NULL DEFAULT NULL,
  `idtrungtam` INT NULL DEFAULT NULL,
  `idkhachhang` INT NULL DEFAULT NULL,
  `iddieutri` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `khachhang`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `khachhang` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `khachhang` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `ten` VARCHAR(50) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `ngaysinh` DATE NULL DEFAULT NULL,
  `sdt` VARCHAR(15) NULL DEFAULT NULL,
  `diachi` VARCHAR(100) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `nghenghiep` VARCHAR(255) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `sobhyt` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `kho`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `kho` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `kho` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `idtrungtam` INT NOT NULL,
  `ten` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `nhacungcap`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `nhacungcap` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `nhacungcap` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `ten` VARCHAR(255) NOT NULL,
  `diachi` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `nhanvien`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `nhanvien` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `nhanvien` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `checkcode` TINYINT NOT NULL,
  `ten` VARCHAR(255) NOT NULL,
  `ngaysinh` DATETIME NOT NULL,
  `vitri` VARCHAR(255) NOT NULL,
  `bangcap` VARCHAR(255) NOT NULL,
  `luong` INT NOT NULL,
  `diachi` VARCHAR(255) NOT NULL,
  `sdt` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `username` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `quyen` ENUM('user', 'premium', 'admin') NOT NULL DEFAULT 'user',
  `loginfirst` INT NOT NULL,
  `code` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 21
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `phieunhap`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `phieunhap` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `phieunhap` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `idnhanvien` INT NOT NULL,
  `trangthai` TINYINT NOT NULL,
  `ngay` DATETIME NOT NULL,
  `tongtien` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 31
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `phieuxuat`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `phieuxuat` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `phieuxuat` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `idnhanvien` INT NOT NULL,
  `idtrungtam` INT NOT NULL,
  `ngay` VARCHAR(255) NOT NULL,
  `tongtien` INT NOT NULL,
  `trangthai` TINYINT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 9
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `thongtinhoatdong`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `thongtinhoatdong` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `thongtinhoatdong` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `tieude` TEXT NULL DEFAULT NULL,
  `thoigianbatdau` DATE NULL DEFAULT NULL,
  `thoigianketthuc` DATE NULL DEFAULT NULL,
  `idtrungtam` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `trungtam`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `trungtam` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `trungtam` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `ten` VARCHAR(255) NOT NULL,
  `duongdaynong` VARCHAR(255) NOT NULL,
  `diachi` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `vacxin`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `vacxin` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `vacxin` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `soluong` INT NOT NULL,
  `ten` VARCHAR(255) NOT NULL,
  `dongia` INT NOT NULL,
  `ngaysanxuat` DATETIME NOT NULL,
  `hansudung` DATETIME NOT NULL,
  `doituongsudung` VARCHAR(255) NOT NULL,
  `solo` VARCHAR(255) NOT NULL,
  `baoquan` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `xuatkho`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `xuatkho` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `xuatkho` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `idnhanvien` INT NOT NULL,
  `idkho` INT NOT NULL,
  `ngay` DATETIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
